export enum AbilityActionEnum {
  CREATE = 'create',
  EDIT = 'edit',
  REMOVE = 'remove',
  UPSERT = 'upsert',
  VIEW = 'view',
  ACCESS = 'access',
  FILTER = 'filter',
}

export enum AbilitySubjectEnum {
  ACCOMODATION = 'accommodation',
  MANAGER_TAB = 'manager_tab',
  ROOM = 'room',
  TENANT = 'tenant',
  CONTRACT = 'contract',
  ROOM_SERVICE = 'room service',
  ACCOMMODATION_SERVICE = 'accommodation service',
  OWNER_ID_CARD = 'owner identity card',
  PAYMENT_INFORMATION = 'payment information',
  OWNER_INFOR = 'owner information',
  LIST_TENANTS = 'list tenants',
  LIST_CONTRACTS = 'list contracts',
  LIST_MANAGERS_OF_OWNER = 'list managers of owner',
  TENANTS = 'tenants',
  REPORT = 'report',
  REQUESTS = 'requests',
  INVOICE = 'invoice',
  RULE = 'rule',
  INVOICE_FILTER_DRAFT = 'invoice draft',
  INVOICE_FILTER_UN_PAID = 'invoice un paid',
  INVOICE_FILTER_PARTIAL_PAID = 'invoice partial paid',
  INVOICE_FILTER_PAID = 'invoice paid',
  ROOM_PROPERTY = 'room property',
}
